apiVersion: v1
kind: PersistentVolumeClaim
metadata:
 name: sample-pvc
 annotations:
    volume.beta.kubernetes.io/storage-class: "managed-nfs-storage"
spec:
 storageClassName: managed-nfs-storage
 accessModes:
   - ReadWriteMany
 resources:
   requests:
     storage: 1Gi
