apiVersion: v1
kind: Pod
metadata:
  labels:
    run: sample
  name: sample
spec:
  containers:
  - image: httpd
    name: sample
    volumeMounts: 
    - name: vol
      mountPath: /usr/local/apache2/htdocs
  volumes:
  - name: vol
    persistentVolumeClaim:
      claimName: sample-pvc
